/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.yangkaibrowser.legacy;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int yk_black=0x7f040000;
        public static final int yk_card_surface=0x7f040002;
        public static final int yk_crimson=0x7f040005;
        public static final int yk_crimson_light=0x7f040006;
        public static final int yk_cursor_color=0x7f04000a;
        public static final int yk_dark_surface=0x7f040001;
        public static final int yk_focus_glow=0x7f040009;
        public static final int yk_gold=0x7f040003;
        public static final int yk_gold_bright=0x7f040004;
        public static final int yk_gray_text=0x7f040008;
        public static final int yk_white=0x7f040007;
    }
    public static final class drawable {
        public static final int btn_focused=0x7f020000;
        public static final int btn_normal=0x7f020001;
        public static final int btn_selector=0x7f020002;
        public static final int edittext_selector=0x7f020003;
        public static final int ic_cursor_pointer=0x7f020004;
        public static final int ic_dragon=0x7f020005;
        public static final int ic_launcher=0x7f020006;
    }
    public static final class id {
        public static final int btn_back=0x7f070002;
        public static final int btn_cursor_toggle=0x7f07000a;
        public static final int btn_downloads=0x7f070009;
        public static final int btn_forward=0x7f070003;
        public static final int btn_go=0x7f070007;
        public static final int btn_home=0x7f070006;
        public static final int btn_menu=0x7f07000b;
        public static final int btn_reload=0x7f070005;
        public static final int btn_tabs=0x7f070008;
        public static final int main_root=0x7f070000;
        public static final int progress_bar=0x7f07000c;
        public static final int status_bar=0x7f07000e;
        public static final int top_toolbar=0x7f070001;
        public static final int tv_brand=0x7f070010;
        public static final int tv_mem_status=0x7f070011;
        public static final int tv_mode_status=0x7f070012;
        public static final int url_input=0x7f070004;
        public static final int virtual_cursor=0x7f07000f;
        public static final int webview_container=0x7f07000d;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int app_tagline=0x7f050001;
        public static final int btn_back=0x7f050003;
        public static final int btn_cursor=0x7f05000a;
        public static final int btn_forward=0x7f050004;
        public static final int btn_home=0x7f050007;
        public static final int btn_menu=0x7f050009;
        public static final int btn_reload=0x7f050005;
        public static final int btn_stop=0x7f050006;
        public static final int btn_tabs=0x7f050008;
        public static final int dialog_title_bookmarks=0x7f050017;
        public static final int dialog_title_clear_data=0x7f050019;
        public static final int dialog_title_diagnostics=0x7f050018;
        public static final int dialog_title_history=0x7f050016;
        public static final int dialog_title_settings=0x7f050014;
        public static final int dialog_title_tabs=0x7f050015;
        public static final int nav_bookmarks=0x7f050010;
        public static final int nav_diagnostics=0x7f050013;
        public static final int nav_downloads=0x7f050011;
        public static final int nav_history=0x7f05000f;
        public static final int nav_settings=0x7f050012;
        public static final int quick_archive=0x7f05000d;
        public static final int quick_news=0x7f05000e;
        public static final int quick_search=0x7f05000b;
        public static final int quick_wiki=0x7f05000c;
        public static final int search_hint=0x7f050002;
        public static final int str_back=0x7f050021;
        public static final int str_bookmarks=0x7f05001c;
        public static final int str_cancel=0x7f050032;
        public static final int str_clear=0x7f050030;
        public static final int str_close=0x7f05002d;
        public static final int str_delete=0x7f05002f;
        public static final int str_diagnostics=0x7f050020;
        public static final int str_download=0x7f050026;
        public static final int str_download_complete=0x7f050027;
        public static final int str_download_failed=0x7f050028;
        public static final int str_downloads=0x7f05001e;
        public static final int str_forward=0x7f050022;
        public static final int str_history=0x7f05001d;
        /**  Standard Action & Status Strings 
 Standard Action & Status Strings in Natural Arabic 
         */
        public static final int str_home=0x7f05001a;
        public static final int str_memory=0x7f05002a;
        public static final int str_network_error=0x7f050029;
        public static final int str_open=0x7f05002e;
        public static final int str_reload=0x7f050023;
        public static final int str_retry=0x7f050025;
        public static final int str_save=0x7f050031;
        public static final int str_search=0x7f05001b;
        public static final int str_settings=0x7f05001f;
        public static final int str_stop=0x7f050024;
        public static final int str_storage=0x7f05002b;
        public static final int str_tabs=0x7f05002c;
    }
    public static final class style {
        public static final int YangKaiDarkTheme=0x7f060000;
    }
}
